runtime: python310
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: 'development'

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 5

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto